version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: chromedriver
    versions:
    - 87.0.4
